### ISSUE TITLE
_SfSparkLineChartState not updating

### ISSUE THREAD

**Issue by husnain067** [biner88/chart_sparkline#8]
The following RangeError was thrown building SfSparkLineChart(dependencies: [_InheritedTheme, _LocalizationsScope-[GlobalKey#1cd93]], state: _SfSparkLineChartState#67f2a):
RenderSparkChart.processDataSource (package:syncfusion_flutter_charts/src/sparkline/renderers/renderer_base.dart:516:33)
#3      RenderSparkChart._refreshSparkChart (package:syncfusion_flutter_charts/src/sparkline/renderers/renderer_base.dart:686:5)
#4      RenderSparkChart.dataCount= (package:syncfusion_flutter_charts/src/sparkline/renderers/renderer_base.dart:176:7)
#5      SfSparkLineChartRenderObjectWidget.updateRenderObject (package:syncfusion_flutter_charts/src/sparkline/renderers/spark_line_renderer.dart:119:9)
#6      RenderObjectElement._performRebuild (package:flutter/src/widgets/framework.dart:5668:12)
#7      RenderObjectElement.update (package:flutter/src/widgets/framework.dart:5647:5)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#9      RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5787:32)
#10     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6445:17)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#14     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#17     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#19     StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#21     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#23     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5787:32)
#24     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6445:17)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#26     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#28     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5787:32)
#29     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6445:17)
#30     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#31     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#34     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#35     StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#37     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#39     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#42     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#43     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#44     StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#47     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#48     StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#51     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#52     StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#53     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#54     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#56     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#57     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#59     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#60     StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#61     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#63     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#64     ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#65     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#67     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#68     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#69     StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#70     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#72     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#73     StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#75     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1243:37)
#76     SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:1148:35)
#77     Iterable.forEach (dart:core/iterable.dart:325:35)
#78     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:1192:24)
#79     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:1126:7)
#80     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#82     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#83     ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#84     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#85     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#86     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#87     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5787:32)
#88     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6445:17)
#89     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:228:11)
#90     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#91     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#92     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#93     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#94     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#95     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#96     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#97     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#98     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#99     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#100    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#101    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#102    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#103    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#104    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#105    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#106    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#107    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#108    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#109    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#110    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#111    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#113    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#114    StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#115    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#116    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#117    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#118    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#119    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#120    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#121    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#122    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#123    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#124    StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#125    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#126    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#127    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#128    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#129    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#130    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#131    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#132    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#133    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#134    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#135    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#136    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#137    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#138    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#139    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#140    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#141    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#142    StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#143    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#144    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#145    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#146    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#147    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#148    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#149    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#150    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
(elided 3 frames from dart:async)

**Comment by husnain067** [comment]
i'm using this library for showing graphs in Listview whenever i update the Listview or apply some sorting on Listview the SfSparkLineChart.custom is always throw above exception.
